### ISSUE TITLE
不同进程能监听同一个端口吗？

### ISSUE THREAD

**Issue by Unimmms** [ddrpa/corgi#1]
在V2EX来的。这个工具我还没尝试，但是我在V2EX上看到，有人出现了端口占用问题。这个工具的是可以在，比如我已经在8080启动了一个服务的情况下，继续监听8080端口。还是单独监听某一个端口，在以便获取到请求方的请求内容？

**Comment by ddrpa** [comment]
按我目前所学，我还不能做到让两个进程监听同一个端口。

调试接口的时候要保持原程序运行，那我只能假设您是在调试某个特定的接口。

因为我接触的场景通常会在应用前再挂上 NGINX，可以在配置里设置转发特定路径的请求。

例如需要调试的应用运行在 8080 端口上，可以让 corgi 运行在 8081，然后让 NGINX 转发（可能会有一些错误，会意即可）：

```nginx
listen 80;
location / {
	proxy_pass app_upstream;
}

location /an/awesome/api/ {
	proxy_pass localhost:8081;
}
```

`--fetch` 参数是用来指示 corgi 将收到的请求原样发送到参数指定的地址去，并将目标的响应送回给请求者（不过我自己几乎不用这个功能，没有详尽地测试过）。


```shell
corgi -p 8081 --fetch http://localhost:8080/an/awesome/api/
```

单纯负载均衡之类的工具也许也能够支持这样分流。

**Comment by Unimmms** [comment]
谢谢，如果用NGINX我就理解了。我还以为这个程序可以在端口已经被占用的情况下，再去监听同样的端口。
